apiVersion: v1
kind: Pod
metadata:
  name: alpineuser
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000
  containers:
  - name: aplineuser
    image: alpine
    command: ["/bin/sleep", "999999"]
