kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: developer
  name: developer-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods"]
  verbs: [ "create", "update", "patch", "delete"]

